services:
  mariadb_dev:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: formulaire-docker
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - mariadb_data_dev:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  mariadb_data_dev:
networks:
  app-network:
    driver: bridge
